# Generated by Django 5.1.2 on 2024-11-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
